language: java
env:
  global:
  - secure: bXmcp9PKyOQZFmc0vWgaPytk84R4wEEeiBltwiV0P2eh1qZ2PFpmuMqAXrgG+748ctbNImQWo4bxRuc8UWgQhoPZfKtUgmhjGN3xqXfrtLTd8PN/mOG90nlSwapwywBoZD1lk0vq4HDNem+Jc/Fht+iDYOdUlSZLnRz6Z7u6tmJSndmr5EKTGExNLH1dug7JBkLHxKv4SL5FzolgAPhWoMlMir/EwayAD0fTe+g85gKbADVm6sA73VX032rxTORXImbYot5OnwDB1lGGCwn5qqKtoyRihiCUpnkNKv+IwrTDoUYWSSQiAt8Xa8H6sG3/NzO5yxXUD3UJwQUpP5QQAoExUGY8svEF0vP95L/I1vh/KJbaw0rHkd2ecyLI+79bJj91Ebk3i0pLvOrulA+hmDX52lM+VdInCRCLbYQeji7N0HZ6mm2dk7CrBTBHf1Oej4dxDfglElCcoSubIM+CZ5fKEAnb7I4CfslThdtKSn+sVa2XRfNuDQMeupM+eLFZT+nSynrHfgKdH29OFVHbwrMTvds/qhvPsHQ6fM5MaaDiF+XbpU97Tmte1cv9ga204W9eg7lHO2DYYgxnmKV+DLaMWHvvadRPDiaQnWsno2PFhaDt3+xblhdf0QwX8Oxl3uUTxiy1YvXGuVP2sKyT87pJeVewiYEDsnDqns1LX1E=
  - secure: c5WsbBE7Xp8cnuoC0cHy5NavZ4556z9fjLlADXj6kT7XppQjdZ/+q5CvgETYCltAphlhI8vG0yRyS7QuGF+VUADl5BVE75rMFFmCjY30f5u6nQqhQUcfx/L/bQRZbjmCQdcPooYvk2AmMln4yg5sTxs/ZnbhfPB0v7j2+wgtSYvXErj6yLVrl5I3R1QvGj2Nfs9xSbQ1beJd+BNtaBRAy9OU0Uzq63HtjrAe2muRSwQy+wFAJTGnJqPN+1eqj0w8nyht+osJgx04G0xvhJoff4/kOu2gWEioFT/tfuCIFVhcra9VO4y1qwob3xqdzOozoZO5cmjqUOpCIZWn0XrqFhZc4kv9AXwNH+M/bgEBfFvF1WrzbiFKxAgifRRFkNm/ZCIyGzMhAqDiARBKuleCI42VD+2LJ1nFJ6wZ1GZP3hL0mzfXQM5YFrZgrchuO2b1HM8YyxrGLpDA+zD3cF4iVuOgHWRl73wdroR+yTF9Js7JcEF6gHz5yqr/brbzcTGRzYInQwg4jwhVhWm5EWH7ir3IINBiBQLvfP0uS2GwqHLOadw9jn7kPoBDdncF8Nv/Xln2pCR6GNWN+6lWTj0QsukjQJ792RMA1Zxtw8ES39KBEBLbEQSxJdahgpW98noWpq3JYQxMpnetrA5DjV9yld55iCxa29aIKJv5xyafm/U=
  - secure: "kkBE4LzLQELWHDxuDFgHf7sF93EDKu5veo+JCQgNoHveTewenC/f5QNmuxJgQMV6MsG3e/6VZGTPGaZKcFAh8meoXNz8uWkYmklmjhM3tqT/HZIa8H1WiRFGG2Vd7nD91A51RNcWIS2PGl2K5y/Nv/1sf4Z60vWjZziiM0B8+mlFEvCXuTZ4eDr9rXgHufoPnub8Y2nwB/gDZA8DqpJcO/U4nEqiBUiOe+nHWr1HhmCf0P3j1y2G40zeKjafdNHn/KfYjMwmy8ye8K0oxgUiwrIfk2fBRrca/MN9T17mF2+64KR1u/DEJjTtZri3+yit4WzG7cHhZbM5y5ekDtKsqYBXSElay+BmKBU7d/S7hRRJey0Bc1hkkew8d0CE6XPDmiBj+xGj89DcxQwUrOY/+5bVvEMzT4fhYUErsb6w7H6A9wl1+gfzUfLE71MOrVrCocomGuTpH0/DQ3umiWvsyLN0Bu+xWRXVv7qZbQL/MS0dij/cYqXg/LCfmeyMaE/nEreQKjFnAiB7G0QmoA063OVZaZWCbYacED0zM89H8Mrc3mtHwPA+bDOdOEygxV1fEyQSY6LLAvRDZaIsSNOnREU0/sdKeFpzMVwzpL7/9JKTSfpe3XjB7Bt+f9kB32WhFXI0Mhhgyf1oRg9X21e5oI1WkXDUavlcCzBtmzSZa1s="
  - secure: "V3z1Yc88NoazfydGuxFNmHwBRYtd7jGum4riUlguVGPDku++UOixkGSF1rg022MpGRef5ubsEzRPe5+nvRzqI6AyVnH3nHEw8jMj+PWINq97pAsQxgiNGYOGZHut0idkwX2OlVVj4dRhFwGvurQeemPTtf/a254h/w53nVx5P87CtqvqrTxUXCMOxrdOrPdFl/OMaPcg66Vzj8n9ax0jUhGbpnxzhgdehBqqOqpmgN20nBFt7sr7eUnbWBq6w93SMCZ9Y0xcSptZx1bYP1SRMgDJEJIoAweA7Pp7GJ5wNbpDXrDDRucfKhhLCiL7ZmZJ3EhMK2gIkz4MLvm1najeZwPgUUlBTb59ACflAOdVFL/0UWNVC9sl+L7EUkNCBWkhh5roKT8GU51C5EknA003Qv9jdbDtwBFNwFXGFy3EMvdga6Zjl8msn2ApEpCtIoCF/+iFw/ssdPdBTDGRn2Q1fUYK0vFHKqRryBY2BYXpi9OtYjAWCHyxChc0CGZt8bjBouqOis9KhM1wzqZtfgPqtMBZQ3JL6jO8mDs4+41qoeowdF2kMWrAVMWuRxyDvl/goPKKrT71BY9WscFRw76AU2AG0E4HMOZe7937tte4zTOgpsSIFaGiezIsrx0k8CwNvLC4QEG3bQQ/Tex4+KcLoXmiKSttCDAu6FHpkWz080M="
  - secure: "IKB3HRMp5LparnaLMhlUyi/Zw5ZB0UlcbafqW1ubgY+rw7+yjOwUtK/RGOCUzv3RMCkr0V1fUJ4puJ/30myGY5Aw1GRF+ze4HqClRYQMzScVdsT/Ul3VevVFKLUL4EB9hW9aUoMKHXDG5Xa6tg4WMoJl9btaXXidvC8lsBPqtchYzo87AF3qLViaebgGJnVXBOxJm1Mxu9Ct/FBXIFBCe0QX6rEsDhymaMmemOn3XI1OPDv6Cj0gUWqvL7Ym3VzG+GhJ0KRdTu8W01e3PT8Eut/q/Ir+mNO5JeL6Lhr1DXOuaDqKuC3T+Hefq36SG5WXVOqZr3B4XueIO+QrG4nU+29m5IAp64E5iAZaip8WlIYW7ZQiW/aR5R9bFicVRvh2IWqc7dgUuhn2YMi5k+UG0RclwKVX4BbbiiOTUbRGqiQFXQRboMn2JQoidydhIVHvSe5333BpUY0zsDl7veGFgyiI0l57P7yKQZtQ4+w7q6UbzaY1HUNBl1Ruif9FUhY6UsQ6OiXE8tbmiKoMUKImrdNKgic2rgitSeSo2dB6lRS2Eox6tr0v0p0d/P8G/qMSVTKvz5+ON7AN6kPFXPNetgL+1WPp7WfhZwIeJVxYa0GMFz+9rUs+m67dkc1hTM96ci+3/t52jL5eqvk8Xh0yM6O0VuE6vub6ymupE1fVVCo="
  - secure: "h8Hb1inlUMf02JcMGL8yuIk4GxBX0i5FR0PJAbsy55qorKdjp9zIA7J1ms/8qJQOuWu+TVEDGsauMR8uSBYfEiPn5SgyoBPXBDWuDvqIF25c/GRc7Z0+hJ0lMglsrOYSMv0mAnv3fI2srRaq2L2AS1XPO7RFwyj7ZoA+Y4sTCdEwIWPRFTW1aeES4WquZJvrir6C7kE7Wz8I3Btm/y8xUUtOEf2QqvG/6BjvJGAyQv+ASBrZ0zBNLxZCaCirlkB0ktErP3FoLUh/0bp5sMJHVhO7nvyRH5LajMan0VsVxx6pcSkGWiSiLFsWdhBYw8FgJVjVKztzm93Tq60KjJZGuoKuDvagKu/5leWOGabapMA41DZNdHQuJnblYkBAGwBavYqgGOe7Yae+knuW/QPISihhBbXs2/Eq9hWR4CTe+PSiHgDKU4f423kv3VCWrFxkKQnj2KwciAkAeycUcWbp/vVt/lLziqWYzO8Ip6BaS4rVirouC4XeKQNGKMX/zSLMZLX85PC6FOg9vQVNzLYrcINAGCU0gQWWC2biThGd+bKJSgD9Z1s5IfpIOmlA/OG/pSPD1KnOCnOWvTZyE/O9DiOXCi9zGa4HjsijaTcw1eovwDdEICnmaVNmDooQW6b0BsGWEBxrjdo3fMZYHsboyqPhSnsPIPRHcoMfgt6hEf0="

matrix:
  include:
  - os: linux
    dist: xenial
    jdk: openjdk8
    sudo: false
    addons:
      apt:
        packages:
        - cmake
        - cmake-data
        - clang-3.8
        - gnupg2
        - openjdk-8-jdk-headless
  - os: osx
    osx_image: xcode9.3
addons:
  homebrew:
    packages:
      - gnupg2
      - swig
    update: true
cache:
  directories:
  - $HOME/.m2
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:timsc/swig-3.0.12 -y; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install swig -y; fi
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/libexec/java_home -V; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "UPDATESTARTUPTTY" | gpg-connect-agent > /dev/null 2>&1; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then alias swig="swig3.0"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export COMPILER=clang++-3.8; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=clang++-3.8; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=clang-3.8; fi
- git submodule init
- git submodule update
script:
- export CMAKE_BUILD_PARALLEL_LEVEL=4
- cd glslang
- git apply ../fix-tokenizer.patch
- python ./update_glslang_sources.py
- cd ..
- cd SPIRV-cross
- git apply ../fix-small-vector.patch
- cd ..
- mkdir -p target/build
- cd target/build
- cmake ../..
- cmake --build . -- -j4
- cd ../..
- ./post-build.sh
- mvn -B package
after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf; fi
- killall -9 gpg-agent
- export GPG_TTY=`tty`
- gpg-agent
- export PINENTRY_MODE="--pinentry-mode=loopback"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -s `which gpg` /usr/local/bin/gpg2; fi
- deploy/before-deploy.sh
- deploy/deploy.sh
