language: java
env:
  global:
  - secure: bXmcp9PKyOQZFmc0vWgaPytk84R4wEEeiBltwiV0P2eh1qZ2PFpmuMqAXrgG+748ctbNImQWo4bxRuc8UWgQhoPZfKtUgmhjGN3xqXfrtLTd8PN/mOG90nlSwapwywBoZD1lk0vq4HDNem+Jc/Fht+iDYOdUlSZLnRz6Z7u6tmJSndmr5EKTGExNLH1dug7JBkLHxKv4SL5FzolgAPhWoMlMir/EwayAD0fTe+g85gKbADVm6sA73VX032rxTORXImbYot5OnwDB1lGGCwn5qqKtoyRihiCUpnkNKv+IwrTDoUYWSSQiAt8Xa8H6sG3/NzO5yxXUD3UJwQUpP5QQAoExUGY8svEF0vP95L/I1vh/KJbaw0rHkd2ecyLI+79bJj91Ebk3i0pLvOrulA+hmDX52lM+VdInCRCLbYQeji7N0HZ6mm2dk7CrBTBHf1Oej4dxDfglElCcoSubIM+CZ5fKEAnb7I4CfslThdtKSn+sVa2XRfNuDQMeupM+eLFZT+nSynrHfgKdH29OFVHbwrMTvds/qhvPsHQ6fM5MaaDiF+XbpU97Tmte1cv9ga204W9eg7lHO2DYYgxnmKV+DLaMWHvvadRPDiaQnWsno2PFhaDt3+xblhdf0QwX8Oxl3uUTxiy1YvXGuVP2sKyT87pJeVewiYEDsnDqns1LX1E=
  - secure: c5WsbBE7Xp8cnuoC0cHy5NavZ4556z9fjLlADXj6kT7XppQjdZ/+q5CvgETYCltAphlhI8vG0yRyS7QuGF+VUADl5BVE75rMFFmCjY30f5u6nQqhQUcfx/L/bQRZbjmCQdcPooYvk2AmMln4yg5sTxs/ZnbhfPB0v7j2+wgtSYvXErj6yLVrl5I3R1QvGj2Nfs9xSbQ1beJd+BNtaBRAy9OU0Uzq63HtjrAe2muRSwQy+wFAJTGnJqPN+1eqj0w8nyht+osJgx04G0xvhJoff4/kOu2gWEioFT/tfuCIFVhcra9VO4y1qwob3xqdzOozoZO5cmjqUOpCIZWn0XrqFhZc4kv9AXwNH+M/bgEBfFvF1WrzbiFKxAgifRRFkNm/ZCIyGzMhAqDiARBKuleCI42VD+2LJ1nFJ6wZ1GZP3hL0mzfXQM5YFrZgrchuO2b1HM8YyxrGLpDA+zD3cF4iVuOgHWRl73wdroR+yTF9Js7JcEF6gHz5yqr/brbzcTGRzYInQwg4jwhVhWm5EWH7ir3IINBiBQLvfP0uS2GwqHLOadw9jn7kPoBDdncF8Nv/Xln2pCR6GNWN+6lWTj0QsukjQJ792RMA1Zxtw8ES39KBEBLbEQSxJdahgpW98noWpq3JYQxMpnetrA5DjV9yld55iCxa29aIKJv5xyafm/U=
  - secure: "kkBE4LzLQELWHDxuDFgHf7sF93EDKu5veo+JCQgNoHveTewenC/f5QNmuxJgQMV6MsG3e/6VZGTPGaZKcFAh8meoXNz8uWkYmklmjhM3tqT/HZIa8H1WiRFGG2Vd7nD91A51RNcWIS2PGl2K5y/Nv/1sf4Z60vWjZziiM0B8+mlFEvCXuTZ4eDr9rXgHufoPnub8Y2nwB/gDZA8DqpJcO/U4nEqiBUiOe+nHWr1HhmCf0P3j1y2G40zeKjafdNHn/KfYjMwmy8ye8K0oxgUiwrIfk2fBRrca/MN9T17mF2+64KR1u/DEJjTtZri3+yit4WzG7cHhZbM5y5ekDtKsqYBXSElay+BmKBU7d/S7hRRJey0Bc1hkkew8d0CE6XPDmiBj+xGj89DcxQwUrOY/+5bVvEMzT4fhYUErsb6w7H6A9wl1+gfzUfLE71MOrVrCocomGuTpH0/DQ3umiWvsyLN0Bu+xWRXVv7qZbQL/MS0dij/cYqXg/LCfmeyMaE/nEreQKjFnAiB7G0QmoA063OVZaZWCbYacED0zM89H8Mrc3mtHwPA+bDOdOEygxV1fEyQSY6LLAvRDZaIsSNOnREU0/sdKeFpzMVwzpL7/9JKTSfpe3XjB7Bt+f9kB32WhFXI0Mhhgyf1oRg9X21e5oI1WkXDUavlcCzBtmzSZa1s="
  - secure: "V3z1Yc88NoazfydGuxFNmHwBRYtd7jGum4riUlguVGPDku++UOixkGSF1rg022MpGRef5ubsEzRPe5+nvRzqI6AyVnH3nHEw8jMj+PWINq97pAsQxgiNGYOGZHut0idkwX2OlVVj4dRhFwGvurQeemPTtf/a254h/w53nVx5P87CtqvqrTxUXCMOxrdOrPdFl/OMaPcg66Vzj8n9ax0jUhGbpnxzhgdehBqqOqpmgN20nBFt7sr7eUnbWBq6w93SMCZ9Y0xcSptZx1bYP1SRMgDJEJIoAweA7Pp7GJ5wNbpDXrDDRucfKhhLCiL7ZmZJ3EhMK2gIkz4MLvm1najeZwPgUUlBTb59ACflAOdVFL/0UWNVC9sl+L7EUkNCBWkhh5roKT8GU51C5EknA003Qv9jdbDtwBFNwFXGFy3EMvdga6Zjl8msn2ApEpCtIoCF/+iFw/ssdPdBTDGRn2Q1fUYK0vFHKqRryBY2BYXpi9OtYjAWCHyxChc0CGZt8bjBouqOis9KhM1wzqZtfgPqtMBZQ3JL6jO8mDs4+41qoeowdF2kMWrAVMWuRxyDvl/goPKKrT71BY9WscFRw76AU2AG0E4HMOZe7937tte4zTOgpsSIFaGiezIsrx0k8CwNvLC4QEG3bQQ/Tex4+KcLoXmiKSttCDAu6FHpkWz080M="

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    sudo: false
    addons:
      apt:
        sources:
        - sourceline: ppa:teward/swig3.0
        - sourceline: ppa:george-edison55/precise-backports
        - sourceline: ppa:ubuntu-toolchain-r/test
        - llvm-toolchain-precise-3.6
        packages:
        - swig3.0
        - cmake
        - cmake-data
        - clang-3.6
  - os: osx
    osx_image: xcode7.3
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/libexec/java_home -V; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then alias swig="swig3.0"; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export COMPILER=clang++-3.6; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=clang++-3.6; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=clang-3.6; fi
- git submodule init
- git submodule update
script:
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cd ..
- mvn package
after_success:
- deploy/before-deploy.sh
- deploy/deploy-artifacts.sh
